spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: root
    username: root
    jdbc-url: jdbc:mysql://127.0.0.1:3306/test_mybatis_plus?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    slave1:
      password: root
      username: root
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test_mybatis_plus?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    slave2:
      password: root
      username: root
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test_mybatis_plus?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC